import type { AppLocale } from "@/lib/locale";
import { pickLocale } from "@/lib/locale";

export function getSignalWriterCopy(locale: AppLocale) {
  return pickLocale(locale, {
    ko: {
      eyebrow: "Signal Writer",
      title: "오늘 쓸 만한 기사에서 Threads 초안을 만드는 공간",
      description:
        "Info Hub에서 모은 신호 중 지금 글로 풀기 좋은 기사만 골라 보여주고, 선택한 카드 하나를 Threads용 초안으로 바꿉니다.",
      coreMode: "간단 모드에서도 이 탭은 그대로 사용할 수 있습니다.",
      fullMode: "전체 모드에서는 Info Hub와 같이 열어 흐름을 이어가기 좋습니다.",
      refresh: "시그널 새로고침",
      loading: "오늘 쓸 만한 시그널을 고르는 중입니다.",
      loadError: "시그널 목록을 불러오지 못했습니다.",
      empty: "오늘 바로 글로 만들 만한 시그널이 아직 없습니다.",
      pages: {
        select: "1. 시그널 선택",
        generate: "2. 생성 중",
        result: "3. 결과",
      },
      cards: {
        why: "왜 지금 중요한가",
        source: "출처",
        published: "발행 시각",
        selected: "선택됨",
      },
      modes: {
        title: "생성 모드",
        description: "요약형보다 관점형과 바이럴형이 계정 성장에는 더 잘 맞습니다.",
        "news-brief": {
          label: "뉴스 요약형",
          description: "핵심 변화와 의미를 빠르게 정리합니다.",
        },
        insight: {
          label: "인사이트형",
          description: "이 변화가 실무에 미치는 영향을 강조합니다.",
        },
        opinion: {
          label: "의견형",
          description: "내 해석과 판단을 앞세운 글로 만듭니다.",
        },
        viral: {
          label: "바이럴형",
          description: "저장/공유를 부르는 훅과 관점을 우선합니다.",
        },
      },
      recommendation: {
        title: "추천 생성 기준",
        apply: "추천값 적용",
        mode: "추천 모드",
        runner: "추천 러너",
        criteria: "추천 기준",
      },
      runners: {
        title: "AI 생성기 선택",
        description: "직접 원하는 AI를 고르거나, 자동 선택으로 가장 적합한 러너를 쓰게 할 수 있습니다.",
        auto: {
          label: "자동 선택",
          description: "사용 가능한 AI 중 가장 적합한 러너를 고릅니다.",
        },
        claude: {
          label: "Claude",
          description: "훅과 관점형 글에 강합니다.",
        },
        codex: {
          label: "Codex",
          description: "구조화와 실무형 정리에 강합니다.",
        },
        gemini: {
          label: "Gemini",
          description: "빠른 요약과 짧은 초안에 잘 맞습니다.",
        },
        openai: {
          label: "OpenAI",
          description: "API key가 있을 때 쓰는 클라우드 fallback입니다.",
        },
        template: {
          label: "템플릿",
          description: "AI 없이 규칙 기반 초안을 만듭니다.",
        },
        available: "사용 가능",
        unavailable: "준비 필요",
        selected: "선택됨",
        recommended: "추천",
      },
      cta: {
        choose: "이 카드 선택",
        generate: "선택한 기사로 초안 생성",
        back: "시그널 목록으로 돌아가기",
        regenerate: "다시 생성",
      },
      generate: {
        title: "Threads 초안 생성 중",
        description:
          "기사 핵심을 정리하고, 글의 각도를 잡고, 후킹 문장과 본문을 묶는 중입니다.",
        processing: "생성 중...",
        done: "생성 완료",
        stages: [
          "기사 신호 정리",
          "핵심 포인트 추출",
          "중복/노이즈 정리",
          "훅과 글 구조 작성",
          "최종 초안 마감",
        ],
      },
      result: {
        title: "생성된 초안",
        mode: "생성 모드",
        runner: "생성 러너",
        angle: "글 각도",
        targetAudience: "이 글이 맞는 독자",
        hook: "훅",
        hookVariants: "훅 3개",
        shortPost: "짧은 버전",
        thread: "쓰레드 버전",
        hashtags: "해시태그",
        whyNow: "왜 지금 올리기 좋은가",
        postingTips: "올릴 때 팁",
        quality: "바이럴 품질 점수",
        qualityTotal: "총점",
        qualityLevels: {
          rough: "초안 수준",
          solid: "게시 가능",
          strong: "강한 초안",
        },
        visuals: "업로드용 이미지",
        sourceImage: "원문 참고 이미지",
        generatedCover: "자동 생성 커버",
        sourceImageHint: "원문에 붙은 대표 이미지가 있을 때만 참고용으로 보여줍니다.",
        generatedCoverHint: "이 커버는 지금 글의 각도에 맞춰 자동 생성한 업로드용 이미지입니다.",
        visualStrategy: "이미지 방향",
        openSourceImage: "원문 이미지 열기",
        downloadCover: "커버 다운로드",
        noSourceImage: "이 시그널에는 바로 쓸 수 있는 원문 이미지가 없습니다.",
        saved: "로컬 저장 경로",
        sourceModels: {
          claude: "Claude 생성",
          codex: "Codex 생성",
          gemini: "Gemini 생성",
          openai: "OpenAI 생성",
          template: "템플릿 생성",
        },
        copyShort: "짧은 글 복사",
        copyThread: "쓰레드 복사",
        copyHook: "훅 복사",
      },
    },
    en: {
      eyebrow: "Signal Writer",
      title: "Turn daily news signals into Threads-ready drafts",
      description:
        "Signal Writer picks the 4-5 stories most worth writing about right now, then turns one selected card into a draft you can publish on Threads.",
      coreMode: "This tab stays useful even in simple mode.",
      fullMode: "In full mode, it works especially well next to Info Hub.",
      refresh: "Refresh signals",
      loading: "Picking the best signals for today.",
      loadError: "Failed to load the signal list.",
      empty: "There are no strong signals to write from right now.",
      pages: {
        select: "1. Select Signal",
        generate: "2. Generating",
        result: "3. Result",
      },
      cards: {
        why: "Why this matters now",
        source: "Source",
        published: "Published",
        selected: "Selected",
      },
      modes: {
        title: "Draft mode",
        description: "Insight, opinion, and viral modes usually perform better than a plain summary.",
        "news-brief": {
          label: "News brief",
          description: "Fast summary of what changed and why it matters.",
        },
        insight: {
          label: "Insight",
          description: "Translate the signal into workflow impact.",
        },
        opinion: {
          label: "Opinion",
          description: "Lead with your take instead of the headline.",
        },
        viral: {
          label: "Viral",
          description: "Optimize for hook strength and shareability.",
        },
      },
      recommendation: {
        title: "Recommended setup",
        apply: "Use recommendation",
        mode: "Recommended mode",
        runner: "Recommended runner",
        criteria: "Why this setup",
      },
      runners: {
        title: "AI runner",
        description: "Pick a specific AI writer, or let the app choose the best available runner automatically.",
        auto: {
          label: "Auto",
          description: "Choose the best available runner for this draft.",
        },
        claude: {
          label: "Claude",
          description: "Best for hooks and stronger point of view.",
        },
        codex: {
          label: "Codex",
          description: "Best for structured, practical drafts.",
        },
        gemini: {
          label: "Gemini",
          description: "Best for fast summaries and concise first drafts.",
        },
        openai: {
          label: "OpenAI",
          description: "Cloud fallback when the API key is configured.",
        },
        template: {
          label: "Template",
          description: "Rule-based fallback without AI.",
        },
        available: "Available",
        unavailable: "Needs setup",
        selected: "Selected",
        recommended: "Recommended",
      },
      cta: {
        choose: "Choose this card",
        generate: "Generate draft from selected signal",
        back: "Back to signals",
        regenerate: "Generate again",
      },
      generate: {
        title: "Generating your Threads draft",
        description:
          "The app is extracting the core signal, shaping the angle, and writing a more postable version.",
        processing: "Generating...",
        done: "Done",
        stages: [
          "Collecting the signal",
          "Extracting key points",
          "Removing noise and overlap",
          "Writing the hook and body",
          "Finalizing the post",
        ],
      },
      result: {
        title: "Generated draft",
        mode: "Draft mode",
        runner: "AI runner",
        angle: "Post angle",
        targetAudience: "Best audience",
        hook: "Hook",
        hookVariants: "Three hook options",
        shortPost: "Short post",
        thread: "Thread version",
        hashtags: "Hashtags",
        whyNow: "Why this is timely",
        postingTips: "Posting tips",
        quality: "Virality score",
        qualityTotal: "Total",
        qualityLevels: {
          rough: "Needs work",
          solid: "Postable",
          strong: "Strong draft",
        },
        visuals: "Upload-ready visuals",
        sourceImage: "Source reference image",
        generatedCover: "Generated cover card",
        sourceImageHint: "Shown only when the original article exposes a usable reference image.",
        generatedCoverHint: "This cover is generated from the post angle so you can upload it directly.",
        visualStrategy: "Visual direction",
        openSourceImage: "Open source image",
        downloadCover: "Download cover",
        noSourceImage: "This signal does not expose a usable source image.",
        saved: "Saved locally",
        sourceModels: {
          claude: "Generated with Claude",
          codex: "Generated with Codex",
          gemini: "Generated with Gemini",
          openai: "Generated with OpenAI",
          template: "Generated with template fallback",
        },
        copyShort: "Copy short post",
        copyThread: "Copy thread",
        copyHook: "Copy hook",
      },
    },
  });
}
