import type { AppLocale } from "@/lib/locale";
import { pickLocale } from "@/lib/locale";

export function getSignalWriterCopy(locale: AppLocale) {
  return pickLocale(locale, {
    ko: {
      eyebrow: "Signal Writer",
      title: "오늘 쓸 만한 기사에서 Threads 초안을 만드는 공간",
      description:
        "Info Hub에서 모은 신호 중 지금 글로 풀기 좋은 기사만 골라 보여주고, 선택한 카드 하나를 Threads용 초안으로 바꿉니다.",
      coreMode: "간단 모드에서도 이 탭은 그대로 사용할 수 있습니다.",
      fullMode: "전체 모드에서는 Info Hub와 같이 열어 흐름을 이어가기 좋습니다.",
      refresh: "시그널 새로고침",
      loading: "오늘 쓸 만한 시그널을 고르는 중입니다.",
      loadError: "시그널 목록을 불러오지 못했습니다.",
      empty: "오늘 바로 글로 만들 만한 시그널이 아직 없습니다.",
      pages: {
        select: "1. 시그널 선택",
        generate: "2. 생성 중",
        result: "3. 결과",
      },
      cards: {
        why: "왜 지금 중요한가",
        source: "출처",
        published: "발행 시각",
        selected: "선택됨",
      },
      cta: {
        choose: "이 카드 선택",
        generate: "선택한 기사로 초안 생성",
        back: "시그널 목록으로 돌아가기",
        regenerate: "다시 생성",
      },
      generate: {
        title: "Threads 초안 생성 중",
        description:
          "기사 핵심을 정리하고, 글의 각도를 잡고, 후킹 문장과 본문을 묶는 중입니다.",
        processing: "생성 중...",
        done: "생성 완료",
        stages: [
          "기사 신호 정리",
          "핵심 포인트 추출",
          "중복/노이즈 정리",
          "훅과 글 구조 작성",
          "최종 초안 마감",
        ],
      },
      result: {
        title: "생성된 초안",
        hook: "훅",
        shortPost: "짧은 버전",
        thread: "쓰레드 버전",
        hashtags: "해시태그",
        whyNow: "왜 지금 올리기 좋은가",
        postingTips: "올릴 때 팁",
        visuals: "업로드용 이미지",
        sourceImage: "원문 참고 이미지",
        generatedCover: "자동 생성 커버",
        sourceImageHint: "원문에 붙은 대표 이미지가 있을 때만 참고용으로 보여줍니다.",
        generatedCoverHint: "이 커버는 지금 글의 각도에 맞춰 자동 생성한 업로드용 이미지입니다.",
        visualStrategy: "이미지 방향",
        openSourceImage: "원문 이미지 열기",
        downloadCover: "커버 다운로드",
        noSourceImage: "이 시그널에는 바로 쓸 수 있는 원문 이미지가 없습니다.",
        saved: "로컬 저장 경로",
        sourceModelOpenAi: "OpenAI 생성",
        sourceModelTemplate: "템플릿 생성",
        copyShort: "짧은 글 복사",
        copyThread: "쓰레드 복사",
      },
    },
    en: {
      eyebrow: "Signal Writer",
      title: "Turn daily news signals into Threads-ready drafts",
      description:
        "Signal Writer picks the 4-5 stories most worth writing about right now, then turns one selected card into a draft you can publish on Threads.",
      coreMode: "This tab stays useful even in simple mode.",
      fullMode: "In full mode, it works especially well next to Info Hub.",
      refresh: "Refresh signals",
      loading: "Picking the best signals for today.",
      loadError: "Failed to load the signal list.",
      empty: "There are no strong signals to write from right now.",
      pages: {
        select: "1. Select Signal",
        generate: "2. Generating",
        result: "3. Result",
      },
      cards: {
        why: "Why this matters now",
        source: "Source",
        published: "Published",
        selected: "Selected",
      },
      cta: {
        choose: "Choose this card",
        generate: "Generate draft from selected signal",
        back: "Back to signals",
        regenerate: "Generate again",
      },
      generate: {
        title: "Generating your Threads draft",
        description:
          "The app is extracting the core signal, shaping the angle, and writing a more postable version.",
        processing: "Generating...",
        done: "Done",
        stages: [
          "Collecting the signal",
          "Extracting key points",
          "Removing noise and overlap",
          "Writing the hook and body",
          "Finalizing the post",
        ],
      },
      result: {
        title: "Generated draft",
        hook: "Hook",
        shortPost: "Short post",
        thread: "Thread version",
        hashtags: "Hashtags",
        whyNow: "Why this is timely",
        postingTips: "Posting tips",
        visuals: "Upload-ready visuals",
        sourceImage: "Source reference image",
        generatedCover: "Generated cover card",
        sourceImageHint: "Shown only when the original article exposes a usable reference image.",
        generatedCoverHint: "This cover is generated from the post angle so you can upload it directly.",
        visualStrategy: "Visual direction",
        openSourceImage: "Open source image",
        downloadCover: "Download cover",
        noSourceImage: "This signal does not expose a usable source image.",
        saved: "Saved locally",
        sourceModelOpenAi: "Generated with OpenAI",
        sourceModelTemplate: "Generated with template fallback",
        copyShort: "Copy short post",
        copyThread: "Copy thread",
      },
    },
  });
}
